security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            access_denied_handler: App\Security\AccessDeniedHandler
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_login_success
                always_use_default_target_path: true
            logout:
                path: app_logout
                target: app_home

    role_hierarchy:
        ROLE_ADMIN:  [ROLE_TEAM, ROLE_MEMBER, ROLE_USER]
        ROLE_TEAM:   [ROLE_MEMBER, ROLE_USER]
        ROLE_MEMBER: [ROLE_USER]

    access_control:
        - { path: ^/admin/team, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_TEAM }
    #   - { path: ^/members, roles: ROLE_MEMBER }
